print("i wake up ")
print("i brush my teeth")
print("i take a bath ")
print("i go to school")
print("i return from school ")
print("i play games ")
print("i go out for cycling ")
print("i eat dinner ")
print("i go to sleep ")
